### ISSUE TITLE
Discovery: testnet-vico

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/krang#2]
notes about things to keep in mind / what has been figured out / identified

well having set up these testnet bits and bobs again have highlighted all the things that need to be solved.
now that host has sorted out VLAN (sort of, I've paid for it, need to actually jump on the other box and config interfaces), will be able to setup the multi-tenant container k8s platform using OpenStack/Hyperd.  

once that is in place it'll be a continuous process of creating docker images to fit the goals in the readme.

things learnt this time around:  
  * cgroups to control process rss usage / luckily docker can take care of this, imagine k8s has knobs to turn too - want quantity of miners however not to max resources (rss) usage
  * discovering new metrics to measure
    - transactions / second
    - transaction time from broadcast to inclusion in a block
    - transaction size over time
    - something about mixin size and what that does for blocks and time to transmit etc
    - resources used by everything, daemon, walletd, miners, pool, etc
  * order of operations
  * support commit, branch, repo auto compile, build, deploy for everything - if it can be reached via the browser (GitHub), it can be reached automatically and pressing buttons can make it go from _"this commit"_ to _"it's running"_ I want krang to be the equiv of magic in terms of wonder and amazement at how easy things are and what happens
  * dashboards and exposing everything via HTTPS is going to be the winning thing for the whole project.

thanks Rock for the prompt to write this down, it's valuable to do that every once and a while, I will keep doing this to make it a habit!

**Comment by 4Reallive** [comment]
sounds like we need to catch up on Discord. I'm just starting to get my flow going, ill DM you to discuss this one.

**Comment by SoreGums** [comment]
ibmc got there first of course

checkout https://github.com/brandonlehmann/turtlecoin-blockexplorer-cache

This issue is done, all notes have been made and new [testnets](https://github.com/turtlecoin/testnet) are rolling out with a complete Docker container solution. see #7
